from typing import Any, Callable, Dict, Optional, Union, overload as Overload, List, Tuple, Self

class LLSE_Block:
    def __init__(self, *args) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def pos(self) -> IntPos: ...
    @property
    def tileData(self) -> int: ...
    @property
    def variant(self) -> int: ...
    @property
    def translucency(self) -> float: ...
    @property
    def thickness(self) -> float: ...
    @property
    def isAir(self) -> bool: ...
    @property
    def isBounceBlock(self) -> bool: ...
    @property
    def isButtonBlock(self) -> bool: ...
    @property
    def isCropBlock(self) -> bool: ...
    @property
    def isDoorBlock(self) -> bool: ...
    @property
    def isFenceBlock(self) -> bool: ...
    @property
    def isFenceGateBlock(self) -> bool: ...
    @property
    def isThinFenceBlock(self) -> bool: ...
    @property
    def isHeavyBlock(self) -> bool: ...
    @property
    def isStemBlock(self) -> bool: ...
    @property
    def isSlabBlock(self) -> bool: ...
    @property
    def isUnbreakable(self) -> bool: ...
    @property
    def isWaterBlockingBlock(self) -> bool: ...
    def getNbt(self) -> 'NbtCompound': ...
    def setNbt(self, nbt: 'NbtCompound') -> bool: ...
    def getBlockState(self) -> dict: ...
    def hasContainer(self) -> bool: ...
    def getContainer(self) -> 'LLSE_Container': ...
    def hasBlockEntity(self) -> bool: ...
    def getBlockEntity(self) -> 'LLSE_BlockEntity': ...
    def removeBlockEntity(self) -> bool: ...
    def destroy(self, drop: bool) -> bool: ...
    def getTag(self) -> 'NbtCompound': ...
    def setTag(self, nbt: 'NbtCompound') -> bool: ...
    
class LLSE_BlockEntity:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def pos(self) -> Any: ...
    @property
    def type(self) -> int: ...
    def setNbt(self, nbt: Any) -> bool: ...
    def getNbt(self) -> NbtCompound: ...
    def getBlock(self) -> 'LLSE_Block': ...
    
class LLSE_Command:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def registered(self) -> bool: ...
    def setEnum(self, enumName: str, enumValues: list[str]) -> str: ...
    def setAlias(self, alias: str) -> bool: ...
    def mandatory(self, name: str, type: int, enumName: str = ..., identifier: str = ..., option: int = ...) -> bool: ...
    def optional(self, name: str, type: int, enumName: str = ..., identifier: str = ..., option: int = ...) -> bool: ...
    def setSoftEnum(self, name: str, values: list[str]) -> bool: ...
    def addSoftEnumValues(self, name: str, values: list[str]) -> bool: ...
    def removeSoftEnumValues(self, name: str, values: list[str]) -> bool: ...
    def getSoftEnumValues(self, name: str) -> list[str]: ...
    def getSoftEnumNames(self) -> list[str]: ...
    @Overload
    def overload(self, *params: str) -> bool: ...
    @Overload
    def overload(self, *params: int) -> bool: ...
    @Overload
    def overload(self, params: list[str]) -> bool: ...
    @Overload
    def overload(self, params: list[int]) -> bool: ...
    def setCallback(self, callback: Any) -> bool: ...
    def setup(self, callback: Any = ...) -> bool: ...

class LLSE_CommandOrigin:
    def __init__(self) -> None: ...
    @property
    def type(self) -> int: ...
    @property
    def typeName(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def pos(self) -> Any: ...
    @property
    def blockPos(self) -> Any: ...
    @property
    def entity(self) -> Any: ...
    @property
    def player(self) -> LLSE_Player|None: ...
    def getNbt(self) -> Any: ...
    def toString(self) -> str: ...

class LLSE_CommandOutput:
    def __init__(self) -> None: ...
    @property
    def empty(self) -> bool: ...
    @property
    def successCount(self) -> int: ...
    @Overload
    def success(self) -> bool: ...
    @Overload
    def success(self, msg: str) -> bool: ...
    @Overload
    def success(self, msg: str, params: list) -> bool: ...
    @Overload
    def addMessage(self, msg: str) -> bool: ...
    @Overload
    def addMessage(self, msg: str, params: list) -> bool: ...
    @Overload
    def addMessage(self, msg: str, params: list, msgType: int) -> bool: ...
    @Overload
    def error(self, msg: str) -> bool: ...
    @Overload
    def error(self, msg: str, params: list) -> bool: ...
    def toString(self) -> str: ...

class OriginType:
    Player = 0
    Block = 1
    MinecartBlock = 2
    DevConsole = 3
    Test = 4
    AutomationPlayer = 5
    ClientAutomation = 6
    DedicatedServer = 7
    Entity = 8
    Virtual = 9
    GameArgument = 10
    EntityServer = 11
    Precompiled = 12
    GameDirectorEntity = 13
    Script = 14
    Executor = 15

class LLSE_Container:
    @property
    def size(self) -> int: ...
    @property
    def type(self) -> str: ...
    @Overload
    def addItem(self, item: Any) -> bool: ...
    @Overload
    def addItem(self, item: Any, amount: int) -> bool: ...
    def addItemToFirstEmptySlot(self, item: Any) -> bool: ...
    def hasRoomFor(self, item: Any) -> bool: ...
    def removeItem(self, slot: int, amount: int) -> bool: ...
    def getItem(self, slot: int) -> Any: ...
    def setItem(self, slot: int, item: LLSE_Item) -> bool: ...
    def getAllItems(self) -> list[LLSE_Item]: ...
    def removeAllItems(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    # 兼容性函数
    def getSlot(self, slot: int) -> Any: ...
    def getAllSlots(self) -> list[Any]: ...

class data:
    @staticmethod
    def xuid2name(xuid: str) -> str: ...
    @staticmethod
    def name2xuid(name: str) -> str: ...
    @staticmethod
    def xuid2uuid(xuid: str) -> str: ...
    @staticmethod
    def name2uuid(name: str) -> str: ...
    @staticmethod
    def getAllPlayerInfo() -> list[dict]: ...
    @staticmethod
    def fromUuid(uuid: str) -> dict: ...
    @staticmethod
    def fromXuid(xuid: str) -> dict: ...
    @staticmethod
    def fromName(name: str) -> dict: ...
    @staticmethod
    def parseJson(json_str: str) -> Any: ...
    @staticmethod
    def toJson(obj: Any, spaces: int = -1) -> str: ...
    @staticmethod
    def toMD5(data: Any) -> str: ...
    @staticmethod
    def toSHA1(data: Any) -> str: ...
    @staticmethod
    def toBase64(data: Any) -> str: ...
    @staticmethod
    def fromBase64(base64_str: str, is_binary: bool = False) -> Any: ...
    @staticmethod
    def openConfig(path: str, file_type: str = "ini", def_content: str = "") -> Any: ...
    @staticmethod
    def openDB(path: str) -> Any: ...

class money:
    @staticmethod
    def set(player: str, amount: int) -> bool: ...
    @staticmethod
    def get(player: str) -> int: ...
    @staticmethod
    def add(player: str, amount: int) -> bool: ...
    @staticmethod
    def reduce(player: str, amount: int) -> bool: ...
    @staticmethod
    def trans(from_player: str, to_player: str, amount: int, note: str = "") -> bool: ...
    @staticmethod
    def getHistory(player: str, count: int) -> list[dict]: ...
    @staticmethod
    def clearHistory(timeout_days: int) -> bool: ...

class JsonConfigFile:
    def __init__(self, path: str, def_content: str = "{}") -> None: ...
    def init(self, key: str, default_value: Any) -> Any: ...
    def get(self, key: str, default_value: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> bool: ...
    def delete(self, key: str) -> bool: ...
    def reload(self) -> bool: ...
    def close(self) -> bool: ...
    @property
    def path(self) -> str: ...
    def read(self) -> str: ...
    def write(self, content: str) -> bool: ...

class IniConfigFile:
    def __init__(self, path: str, def_content: str = "") -> None: ...
    def init(self, section: str, key: str, default_value: Any) -> Any: ...
    def set(self, section: str, key: str, value: Any) -> bool: ...
    def getStr(self, section: str, key: str, default_value: str = "") -> str: ...
    def getInt(self, section: str, key: str, default_value: int = 0) -> int: ...
    def getFloat(self, section: str, key: str, default_value: float = 0.0) -> float: ...
    def getBool(self, section: str, key: str, default_value: bool = False) -> bool: ...
    def delete(self, section: str, key: str) -> bool: ...
    def reload(self) -> bool: ...
    def close(self) -> bool: ...
    @property
    def path(self) -> str: ...
    def read(self) -> str: ...
    def write(self, content: str) -> bool: ...

class KVDatabase:
    def __init__(self, path: str) -> None: ...
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> bool: ...
    def delete(self, key: str) -> bool: ...
    def close(self) -> bool: ...
    def listKey(self) -> list[str]: ...

class DBSession:
    def __init__(self, params: Any) -> None: ...
    def query(self, sql: str) -> Any: ...
    def exec(self, sql: str) -> Any: ...
    def execute(self, sql: str) -> Any: ...
    def prepare(self, sql: str) -> Any: ...
    def close(self) -> bool: ...
    def isOpen(self) -> bool: ...

class DBStmt:
    @property
    def affectedRows(self) -> int: ...
    @property
    def insertId(self) -> int: ...
    def bind(self, *args: Any) -> Any: ...
    def execute(self) -> Any: ...
    def step(self) -> bool: ...
    def fetch(self) -> dict: ...
    def fetchAll(self) -> Any: ...
    def reset(self) -> Any: ...
    def reexec(self) -> Any: ...
    def clear(self) -> Any: ...

class LLSE_Device:
    def __init__(self) -> None: ...
    @property
    def ip(self) -> str: ...
    @property
    def avgPing(self) -> int: ...
    @property
    def avgPacketLoss(self) -> float: ...
    @property
    def lastPing(self) -> int: ...
    @property
    def lastPacketLoss(self) -> float: ...
    @property
    def os(self) -> str: ...
    @property
    def inputMode(self) -> int: ...
    @property
    def serverAddress(self) -> str: ...
    @property
    def clientId(self) -> str: ...

class LLSE_Entity:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def pos(self) -> 'FloatPos': ...
    @property
    def posDelta(self) -> 'FloatPos': ...
    @posDelta.setter
    def posDelta(self, value: Union['FloatPos', tuple]) -> None: ...
    @property
    def feetPos(self) -> 'FloatPos': ...
    @property
    def blockPos(self) -> 'IntPos': ...
    @property
    def maxHealth(self) -> float: ...
    @property
    def health(self) -> float: ...
    @health.setter
    def health(self, value: float) -> None: ...
    @property
    def canFly(self) -> bool: ...
    @property
    def canFreeze(self) -> bool: ...
    @property
    def canSeeDaylight(self) -> bool: ...
    @property
    def canPickupItems(self) -> bool: ...
    @property
    def inAir(self) -> bool: ...
    @property
    def inWater(self) -> bool: ...
    @property
    def inLava(self) -> bool: ...
    @property
    def inRain(self) -> bool: ...
    @property
    def inSnow(self) -> bool: ...
    @property
    def inWall(self) -> bool: ...
    @property
    def inWaterOrRain(self) -> bool: ...
    @property
    def inWorld(self) -> bool: ...
    @property
    def speed(self) -> float: ...
    @property
    def direction(self) -> 'DirectionAngle': ...
    @property
    def uniqueId(self) -> str: ...
    @property
    def runtimeId(self) -> str: ...
    @property
    def isInvisible(self) -> bool: ...
    @property
    def isInsidePortal(self) -> bool: ...
    @property
    def isTrusting(self) -> bool: ...
    @property
    def isTouchingDamageBlock(self) -> bool: ...
    @property
    def isOnFire(self) -> bool: ...
    @property
    def isOnGround(self) -> bool: ...
    @property
    def isOnHotBlock(self) -> bool: ...
    @property
    def isTrading(self) -> bool: ...
    @property
    def isRiding(self) -> bool: ...
    @property
    def isDancing(self) -> bool: ...
    @property
    def isSleeping(self) -> bool: ...
    @property
    def isAngry(self) -> bool: ...
    @property
    def isBaby(self) -> bool: ...
    @property
    def isMoving(self) -> bool: ...
    @property
    def biomeName(self) -> str: ...
    @property
    def biomeId(self) -> int: ...
    def teleport(self, pos: Union['IntPos', 'FloatPos', tuple], rotation: 'DirectionAngle' = None) -> bool: ...
    def kill(self) -> bool: ...
    def despawn(self) -> bool: ...
    def remove(self) -> bool: ...
    def hurt(self, damage: float, damageType: int = 0, source: 'LLSE_Entity' = None) -> bool: ...
    def heal(self, amount: int) -> bool: ...
    def setAbsorption(self, value: float) -> bool: ...
    def setAttackDamage(self, value: float) -> bool: ...
    def setMaxAttackDamage(self, value: float) -> bool: ...
    def setFollowRange(self, value: float) -> bool: ...
    def setKnockbackResistance(self, value: float) -> bool: ...
    def setLuck(self, value: float) -> bool: ...
    def setMovementSpeed(self, value: float) -> bool: ...
    def setUnderwaterMovementSpeed(self, value: float) -> bool: ...
    def setLavaMovementSpeed(self, value: float) -> bool: ...
    def setMaxHealth(self, value: float) -> bool: ...
    def setFire(self, time: int, isEffect: bool = True) -> bool: ...
    def setOnFire(self, time: int) -> bool: ...
    def stopFire(self) -> bool: ...
    def setScale(self, scale: float) -> bool: ...
    def distanceTo(self, target: Union['LLSE_Entity', 'LLSE_Player', 'IntPos', 'FloatPos', tuple]) -> float: ...
    def distanceToSqr(self, target: Union['LLSE_Entity', 'LLSE_Player', 'IntPos', 'FloatPos', tuple]) -> float: ...
    def isPlayer(self) -> bool: ...
    def toPlayer(self) -> 'LLSE_Player': ...
    def isItemEntity(self) -> bool: ...
    def toItem(self) -> 'LLSE_Item': ...
    def getBlockStandingOn(self) -> 'LLSE_Block': ...
    def getArmor(self) -> 'LLSE_Container': ...
    def hasContainer(self) -> bool: ...
    def getContainer(self) -> 'LLSE_Container': ...
    def refreshItems(self) -> bool: ...
    def getNbt(self) -> 'NbtCompound': ...
    def setNbt(self, nbt: 'NbtCompound') -> bool: ...
    def addTag(self, tag: str) -> bool: ...
    def removeTag(self, tag: str) -> bool: ...
    def hasTag(self, tag: str) -> bool: ...
    def getAllTags(self) -> List[str]: ...
    def getEntityFromViewVector(self, maxDistance: float = 5.25) -> 'LLSE_Entity': ...
    def getBlockFromViewVector(self, includeLiquid: bool = False, solidOnly: bool = False, maxDistance: float = 5.25, fullOnly: bool = False) -> 'LLSE_Block': ...
    def quickEvalMolangScript(self, script: str) -> float: ...
    def getAllEffects(self) -> List[int]: ...
    def addEffect(self, effectId: int, duration: int, level: int, showParticles: bool) -> bool: ...
    def removeEffect(self, effectId: int) -> bool: ...

class LLMoneyEvent:
    Add = 1
    Reduce = 2
    Trans = 3
    Set = 4

class EVENT_TYPES:
    onPreJoin = 0
    onJoin = 1
    onLeft = 2
    onRespawn = 3
    onPlayerDie = 4
    onPlayerCmd = 5
    onChat = 6
    onChangeDim = 7
    onJump = 8
    onSneak = 9
    onPlayerSwing = 10
    onAttackEntity = 11
    onAttackBlock = 12
    onUseItem = 13
    onUseItemOn = 14
    onUseBucketPlace = 15
    onUseBucketTake = 16
    onTakeItem = 17
    onDropItem = 18
    onEat = 19
    onAte = 20
    onConsumeTotem = 21
    onEffectAdded = 22
    onEffectUpdated = 23
    onEffectRemoved = 24
    onStartDestroyBlock = 25
    onDestroyBlock = 26
    onPlaceBlock = 27
    afterPlaceBlock = 28
    onOpenContainer = 29
    onCloseContainer = 30
    onInventoryChange = 31
    onPlayerPullFishingHook = 32
    onPlayerInteractEntity = 33
    onChangeSprinting = 34
    onSetArmor = 35
    onUseRespawnAnchor = 36
    onOpenContainerScreen = 37
    onExperienceAdd = 38
    onBedEnter = 39
    onOpenInventory = 40
    onMobDie = 41
    onMobHurt = 42
    onEntityExplode = 43
    onProjectileHitEntity = 44
    onWitherBossDestroy = 45
    onRide = 46
    onSpawnProjectile = 47
    onProjectileCreated = 48
    onEntityTransformation = 49
    onMobTrySpawn = 50
    onMobSpawned = 51
    onNpcCmd = 52
    onEndermanTakeBlock = 53
    onBlockInteracted = 54
    onBlockChanged = 55
    onBlockExplode = 56
    onRespawnAnchorExplode = 57
    onBlockExploded = 58
    onFireSpread = 59
    onCmdBlockExecute = 60
    onContainerChange = 61
    onProjectileHitBlock = 62
    onRedStoneUpdate = 63
    onHopperSearchItem = 64
    onHopperPushOut = 65
    onPistonTryPush = 66
    onPistonPush = 67
    onFarmLandDecay = 68
    onUseFrameBlock = 69
    onLiquidFlow = 70
    onStepOnPressurePlate = 71
    onChangeArmorStand = 72
    onScoreChanged = 73
    onTick = 74
    onServerStarted = 75
    onConsoleCmd = 76
    onMoneyAdd = 77
    onMoneyReduce = 78
    onMoneyTrans = 79
    onMoneySet = 80
    beforeMoneyAdd = 81
    beforeMoneyReduce = 82
    beforeMoneyTrans = 83
    beforeMoneySet = 84
    onAttack = 85
    onExplode = 86
    onBedExplode = 87
    onMobSpawn = 88
    EVENT_COUNT = 89

class FileOpenMode:
    ReadMode = 0
    WriteMode = 1
    AppendMode = 2

class File:
    ReadMode: int = ...
    WriteMode: int = ...
    AppendMode: int = ...
    def __init__(self, path: str, mode: int, isBinary: Optional[bool] = ...) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def absolutePath(self) -> str: ...
    @property
    def size(self) -> int: ...
    @Overload
    def readSync(self, cnt: int) -> str: ...
    @Overload
    def readSync(self, cnt: int) -> Any: ...  # ByteBuffer
    def readSync(self, cnt: int) -> Union[str, Any]: ...
    def readLineSync(self) -> str: ...
    @Overload
    def readAllSync(self) -> str: ...
    @Overload
    def readAllSync(self) -> Any: ...  # ByteBuffer
    @Overload
    def writeSync(self, data: str) -> bool: ...
    @Overload
    def writeSync(self, data: Any) -> bool: ...  # ByteBuffer
    def writeLineSync(self, data: str) -> bool: ...
    @Overload
    def read(self, cnt: int, callback: Callable[[str], None]) -> bool: ...
    @Overload
    def read(self, cnt: int, callback: Callable[[Any], None]) -> bool: ...  # ByteBuffer
    def readLine(self, callback: Callable[[str], None]) -> bool: ...
    @Overload
    def readAll(self, callback: Callable[[str], None]) -> bool: ...
    @Overload
    def readAll(self, callback: Callable[[Any], None]) -> bool: ...  # ByteBuffer
    @Overload
    def write(self, data: str, callback: Optional[Callable[[bool], None]] = ...) -> bool: ...
    @Overload
    def write(self, data: Any, callback: Optional[Callable[[bool], None]] = ...) -> bool: ...  # ByteBuffer
    def writeLine(self, data: str, callback: Optional[Callable[[bool], None]] = ...) -> bool: ... # type: ignore
    def seekTo(self, pos: int, isRelative: bool) -> bool: ...
    def setSize(self, size: int) -> bool: ...
    def close(self) -> bool: ...
    def isEOF(self) -> bool: ...
    def flush(self) -> bool: ...
    def errorCode(self) -> int: ...
    def clear(self) -> bool: ...
    @staticmethod
    def readFrom(path: str) -> str: ...
    @staticmethod
    def writeTo(path: str, content: str) -> bool: ...
    @staticmethod
    def writeLine(path: str, content: str) -> bool: ...
    @staticmethod
    def createDir(path: str) -> bool: ...
    @staticmethod
    def mkdir(path: str) -> bool: ...
    @staticmethod
    def copy(src: str, dst: str) -> bool: ...
    @staticmethod
    def move(src: str, dst: str) -> bool: ...
    @staticmethod
    def rename(oldPath: str, newPath: str) -> bool: ...
    @staticmethod
    def delete(path: str) -> bool: ...
    @staticmethod
    def exists(path: str) -> bool: ...
    @staticmethod
    def checkIsDir(path: str) -> bool: ...
    @staticmethod
    def getFileSize(path: str) -> int: ...
    @staticmethod
    def getFilesList(path: str) -> List[str]: ...
    @staticmethod
    def open(path: str, mode: int, isBinary: Optional[bool] = ...) -> Any: ...  # File object

class LLSE_Format:
    Black: str = "§0"
    DarkBlue: str = "§1"
    DarkGreen: str = "§2"
    DarkAqua: str = "§3"
    DarkRed: str = "§4"
    DarkPurple: str = "§5"
    Gold: str = "§6"
    Gray: str = "§7"
    DarkGray: str = "§8"
    Blue: str = "§9"
    Green: str = "§a"
    Aqua: str = "§b"
    Red: str = "§c"
    LightPurple: str = "§d"
    Yellow: str = "§e"
    White: str = "§f"
    MinecoinGold: str = "§g"
    Bold: str = "§l"
    Italics: str = "§o"
    Underline: str = "§n"
    StrikeThrough: str = "§m"
    Random: str = "§k"
    Clear: str = "§r"

class LLSE_SimpleForm:
    def setTitle(self, title: str) -> LLSE_SimpleForm: ...
    def setContent(self, content: str) -> LLSE_SimpleForm: ...
    def addButton(self, text: str, image: str = "") -> LLSE_SimpleForm: ...
    def addHeader(self, text: str) -> LLSE_SimpleForm: ...
    def addLabel(self, text: str) -> LLSE_SimpleForm: ...
    def addDivider(self) -> LLSE_SimpleForm: ...

class LLSE_CustomForm:
    def setTitle(self, title: str) -> LLSE_CustomForm: ...
    def setSubmitButton(self, text: str) -> LLSE_CustomForm: ...
    def addHeader(self, text: str) -> LLSE_CustomForm: ...
    def addLabel(self, text: str) -> LLSE_CustomForm: ...
    def addDivider(self) -> LLSE_CustomForm: ...
    @Overload
    def addInput(self, name: str) -> LLSE_CustomForm: ...
    @Overload
    def addInput(self, name: str, placeholder: str) -> LLSE_CustomForm: ...
    @Overload
    def addInput(self, name: str, placeholder: str, default_text: str) -> LLSE_CustomForm: ...
    @Overload
    def addInput(self, name: str, placeholder: str, default_text: str, tooltip: str) -> LLSE_CustomForm: ...
    @Overload
    def addSwitch(self, name: str) -> LLSE_CustomForm: ...
    @Overload
    def addSwitch(self, name: str, default_state: bool) -> LLSE_CustomForm: ...
    @Overload
    def addSwitch(self, name: str, default_state: bool, tooltip: str) -> LLSE_CustomForm: ...
    @Overload
    def addDropdown(self, name: str, options: List[str]) -> LLSE_CustomForm: ...
    @Overload
    def addDropdown(self, name: str, options: List[str], default_index: int) -> LLSE_CustomForm: ...
    @Overload
    def addDropdown(self, name: str, options: List[str], default_index: int, tooltip: str) -> LLSE_CustomForm: ...
    @Overload
    def addSlider(self, name: str, min_value: int, max_value: int) -> LLSE_CustomForm: ...
    @Overload
    def addSlider(self, name: str, min_value: int, max_value: int, step: int) -> LLSE_CustomForm: ...
    @Overload
    def addSlider(self, name: str, min_value: int, max_value: int, step: int, default_value: int) -> LLSE_CustomForm: ...
    @Overload
    def addSlider(self, name: str, min_value: int, max_value: int, step: int, default_value: int, tooltip: str) -> LLSE_CustomForm: ...
    @Overload
    def addStepSlider(self, name: str, steps: List[str]) -> LLSE_CustomForm: ...
    @Overload
    def addStepSlider(self, name: str, steps: List[str], default_index: int) -> LLSE_CustomForm: ...
    @Overload
    def addStepSlider(self, name: str, steps: List[str], default_index: int, tooltip: str) -> LLSE_CustomForm: ...

class i18n:
    @staticmethod
    @Overload
    def tr(key: str) -> str: ...
    @staticmethod
    @Overload
    def tr(key: str, *args: Any) -> str: ...
    @staticmethod
    def tr(key: str, *args: Any) -> str: ...
    @staticmethod
    @Overload
    def trl(locale: str, key: str) -> str: ...
    @staticmethod
    @Overload
    def trl(locale: str, key: str, *args: Any) -> str: ...
    @staticmethod
    def trl(locale: str, key: str, *args: Any) -> str: ...
    @staticmethod
    @Overload
    def get(key: str) -> str: ...
    @staticmethod
    @Overload
    def get(key: str, locale: str) -> str: ...
    @staticmethod
    def get(key: str, locale: str = "") -> str: ...
    @staticmethod
    @Overload
    def load(path: str) -> bool: ...
    @staticmethod
    @Overload
    def load(path: str, default_locale: str) -> bool: ...
    @staticmethod
    @Overload
    def load(path: str, default_locale: str, lang_data: Dict[str, Dict[str, str]]) -> bool: ...
    @staticmethod
    def load(path: str, default_locale: str = "", lang_data: Dict[str, Dict[str, str]] = None) -> bool: ...

class Version:
    Dev = 0
    Beta = 1
    Release = 2

class LLSE_Item:
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def maxCount(self) -> int: ...
    @property
    def aux(self) -> int: ...
    @property
    def damage(self) -> int: ...
    @property
    def lore(self) -> List[str]: ...
    @property
    def attackDamage(self) -> int: ...
    @property
    def maxDamage(self) -> int: ...
    @property
    def maxStackSize(self) -> int: ...
    @property
    def isArmorItem(self) -> bool: ...
    @property
    def isBlock(self) -> bool: ...
    @property
    def isDamageableItem(self) -> bool: ...
    @property
    def isDamaged(self) -> bool: ...
    @property
    def isEnchanted(self) -> bool: ...
    @property
    def isEnchantingBook(self) -> bool: ...
    @property
    def isFireResistant(self) -> bool: ...
    @property
    def isFullStack(self) -> bool: ...
    @property
    def isGlint(self) -> bool: ...
    @property
    def isHorseArmorItem(self) -> bool: ...
    @property
    def isLiquidClipItem(self) -> bool: ...
    @property
    def isMusicDiscItem(self) -> bool: ...
    @property
    def isOffhandItem(self) -> bool: ...
    @property
    def isPotionItem(self) -> bool: ...
    @property
    def isStackable(self) -> bool: ...
    @property
    def isWearableItem(self) -> bool: ...
    def set(self, item: Any) -> bool: ...
    def clone(self) -> Any: ...
    def isNull(self) -> bool: ...
    def setNull(self) -> bool: ...
    def setAux(self, aux: int) -> bool: ...
    def setLore(self, lore: List[str]) -> bool: ...
    def setDisplayName(self, name: str) -> bool: ...
    def setDamage(self, damage: int) -> bool: ...
    def setNbt(self, nbt: Any) -> bool: ...
    def getNbt(self) -> NbtCompound: ...
    def match(self, item: Any) -> bool: ...
    def setTag(self, nbt: Any) -> bool: ...
    def getTag(self) -> NbtCompound: ...

class ll:
    major: int
    minor: int
    revision: int
    status: int
    scriptEngineVersion: str
    language: str
    isWine: bool
    isDebugMode: bool
    isRelease: bool
    isBeta: bool
    isDev: bool
    pluginsRoot: str
    @staticmethod
    def versionString() -> str: ...
    @staticmethod
    def requireVersion() -> bool: ...
    @staticmethod
    def checkVersion() -> bool: ...
    @staticmethod
    def listPlugins() -> List[str]: ...
    @staticmethod
    def getAllPluginInfo() -> List[Dict[str, Any]]: ...
    @staticmethod
    def imports() -> Any: ...
    @staticmethod
    def exports() -> Any: ...
    @staticmethod
    def hasExported() -> bool: ...
    @staticmethod
    def require() -> bool: ...
    @staticmethod
    def eval(code: str) -> Any: ...
    @Overload
    @staticmethod
    def registerPlugin() -> bool: ...
    @Overload
    @staticmethod
    def registerPlugin(name: str) -> bool: ...
    @Overload
    @staticmethod
    def registerPlugin(name: str, description: str) -> bool: ...
    @Overload
    @staticmethod
    def registerPlugin(name: str, description: str, version: Any) -> bool: ...
    @Overload
    @staticmethod
    def registerPlugin(name: str, description: str, version: Any, extraInfo: Dict[str, Any]) -> bool: ...
    @staticmethod
    def getPluginInfo(pluginName: str) -> Dict[str, Any]: ...
    @staticmethod
    def getCurrentPluginInfo() -> Dict[str, Any]: ...
    @staticmethod
    def onUnload(callback: Any) -> None: ...
    @staticmethod
    def version() -> Dict[str, Any]: ...
    @staticmethod
    def versionStatus() -> int: ...

class IntPos:
    def __init__(self, x: int, y: int, z: int, dim: int) -> None: ...
    @property
    def x(self) -> int: ...
    @x.setter
    def x(self, value: int) -> None: ...
    @property
    def y(self) -> int: ...
    @y.setter
    def y(self, value: int) -> None: ...
    @property
    def z(self) -> int: ...
    @z.setter
    def z(self, value: int) -> None: ...
    @property
    def dim(self) -> int: ...
    @property
    def dimid(self) -> int: ...
    @dimid.setter
    def dimid(self, value: int) -> None: ...
    def toString(self) -> str: ...

class FloatPos:
    def __init__(self, x: float, y: float, z: float, dim: int) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, value: float) -> None: ...
    @property
    def dim(self) -> int: ...
    @property
    def dimid(self) -> int: ...
    @dimid.setter
    def dimid(self, value: int) -> None: ...
    def toString(self) -> str: ...

class DirectionAngle:
    def __init__(self, pitch: float, yaw: float) -> None: ...
    @property
    def pitch(self) -> float: ...
    @pitch.setter
    def pitch(self, value: float|int) -> None: ...
    @property
    def yaw(self) -> float: ...
    @yaw.setter
    def yaw(self, value: float|int) -> None: ...
    def toFacing(self) -> int: ...
    def toString(self) -> str: ...
    
class PermType:
    Any = 0
    GameMasters = 1
    Admin = 2
    HostPlayer = 3
    Console = 4
    Internal = 5

class ParamType:
    Int = 0
    Bool = 1
    Float = 2
    Dimension = 3
    String = 4
    Enum = 5
    SoftEnum = 6
    Actor = 7
    Player = 8
    BlockPos = 9
    Vec3 = 10
    RawText = 11
    Message = 12
    JsonValue = 13
    Item = 14
    Block = 15
    BlockState = 16
    Effect = 17
    ActorType = 18
    Command = 19
    RelativeFloat = 20
    IntegerRange = 21
    FilePath = 22
    WildcardInt = 23
    WildcardActor = 24
    Count = 25

class LogLevel:
    Off = 0
    Fatal = 1
    Error = 2
    Warn = 3
    Info = 4
    Debug = 5
    Trace = 6

class logger:
    @staticmethod
    def log(arg: Any) -> bool: ...
    @staticmethod
    def debug(arg: Any) -> bool: ...
    @staticmethod
    def info(arg: Any) -> bool: ...
    @staticmethod
    def warn(arg: Any) -> bool: ...
    @staticmethod
    def warning(arg: Any) -> bool: ...
    @staticmethod
    def error(arg: Any) -> bool: ...
    @staticmethod
    def fatal(arg: Any) -> bool: ...
    @staticmethod
    def setTitle(title: str) -> bool: ...
    @Overload
    @staticmethod
    def setConsole(enabled: bool) -> bool: ...
    @Overload
    @staticmethod
    def setConsole(enabled: bool, level: int) -> bool: ...
    @staticmethod
    def setConsole(enabled: bool, level: int = ...) -> bool: ...
    @Overload
    @staticmethod
    def setFile(filePath: str) -> bool: ...
    @Overload
    @staticmethod
    def setFile(filePath: str, level: int) -> bool: ...
    @staticmethod
    def setFile(filePath: str, level: int = ...) -> bool: ...
    @Overload
    @staticmethod
    def setPlayer(player: Any) -> bool: ...
    @Overload
    @staticmethod
    def setPlayer(player: Any, level: int) -> bool: ...
    @staticmethod
    def setPlayer(player: Any, level: int = ...) -> bool: ...
    @staticmethod
    def setLogLevel(level: int) -> bool: ...

class mc:
    @staticmethod
    def getBDSVersion() -> str: ...
    @staticmethod
    def getServerProtocolVersion() -> int: ...
    @staticmethod
    def runcmd(command: str) -> bool: ...
    @staticmethod
    def runcmdEx(command: str) -> Any: ...
    @staticmethod
    def newCommand(cmd: str, description: str, permission: int = ..., flag: int = ..., alias: str = ...) -> Any: ...
    @staticmethod
    def regPlayerCmd(cmd: str, description: str, callback: Any, level: int = ...) -> Any: ...
    @staticmethod
    def broadcast(message: str, type: int = ...) -> bool: ...
    @staticmethod
    def listen(event: str, callback: Any) -> bool: ...
    @staticmethod
    def getPlayer(name_or_xuid: str) -> Any: ...
    @staticmethod
    def getOnlinePlayers() -> List[Any]: ...
    @staticmethod
    def getAllEntities() -> List[Any]: ...
    @Overload
    @staticmethod
    def getEntities(startPos: IntPos|FloatPos, range: int|float) -> List[Any]: ...
    @Overload
    @staticmethod
    def getEntities(startPos: IntPos|FloatPos, endPos: IntPos|FloatPos) -> List[Any]: ...
    @staticmethod
    def getEntity(uniqueId: int) -> Any: ...
    @Overload
    @staticmethod
    def newItem(name: str, count: int, aux: int = ...) -> LLSE_Item|None: ...
    @Overload
    @staticmethod
    def newItem(nbt: NbtCompound) -> LLSE_Item|None: ...
    @staticmethod
    def spawnMob(name: str, pos: Any, dimensionId: int = ...) -> Any: ...
    @staticmethod
    def spawnItem(item: Any, pos: Any, dimensionId: int = ...) -> Any: ...
    @staticmethod
    def spawnSimulatedPlayer(name: str, pos: Any, dimensionId: int = ...) -> Any: ...
    @staticmethod
    def explode(pos: Any, dimensionId: int, power: float, isFire: bool = ..., isDestroy: bool = ..., isRange: bool = ...) -> bool: ...
    @staticmethod
    def cloneMob(entity: Any) -> Any: ...
    @Overload
    @staticmethod
    def getBlock(pos: Any, dimensionId: int = ...) -> Any: ...
    @Overload
    @staticmethod
    def getBlock(x: int, y: int, z: int, dimensionId: int = ...) -> Any: ...
    @staticmethod
    def setBlock(pos: Any, block: Any, dimensionId: int = ...) -> bool: ...
    @staticmethod
    def spawnParticle(effect: str, pos: Any, dimensionId: int = ...) -> bool: ...
    @staticmethod
    def newSimpleForm() -> LLSE_SimpleForm: ...
    @staticmethod
    def newCustomForm() -> LLSE_CustomForm: ...
    @staticmethod
    def regConsoleCmd(cmd: str, description: str, callback: Any) -> bool: ...
    @staticmethod
    def setMotd(motd: str) -> bool: ...
    @staticmethod
    def sendCmdOutput(output: str) -> bool: ...
    @staticmethod
    def crashBDS() -> None: ...
    @staticmethod
    def setMaxNumPlayers(count: int) -> bool: ...
    @staticmethod
    def newIntPos(x: int, y: int, z: int) -> Any: ...
    @staticmethod
    def newFloatPos(x: float, y: float, z: float) -> Any: ...
    @staticmethod
    def getDisplayObjective(slot: str) -> Any: ...
    @staticmethod
    def clearDisplayObjective(slot: str) -> bool: ...
    @staticmethod
    def getScoreObjective(name: str) -> Any: ...
    @staticmethod
    def newScoreObjective(name: str, displayName: str) -> Any: ...
    @staticmethod
    def removeScoreObjective(name: str) -> bool: ...
    @staticmethod
    def getAllScoreObjectives() -> List[Any]: ...
    @staticmethod
    def getStructure(pos1: Any, pos2: Any, dimensionId: int, ignoreBlocks: bool = ..., ignoreEntities: bool = ...) -> Any: ...
    @staticmethod
    def setStructure(nbt: Any, pos: Any, dimensionId: int = ...) -> bool: ...
    @staticmethod
    def newParticleSpawner(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def getPlayerNbt(player: Any) -> Any: ...
    @staticmethod
    def setPlayerNbt(player: Any, nbt: Any) -> bool: ...
    @staticmethod
    def setPlayerNbtTags(player: Any, nbt: Any) -> bool: ...
    @staticmethod
    def deletePlayerNbt(player: Any) -> bool: ...
    @staticmethod
    def getPlayerScore(player: Any, objective: str) -> int: ...
    @staticmethod
    def setPlayerScore(player: Any, objective: str, value: int) -> bool: ...
    @staticmethod
    def addPlayerScore(player: Any, objective: str, value: int) -> bool: ...
    @staticmethod
    def reducePlayerScore(player: Any, objective: str, value: int) -> bool: ...
    @staticmethod
    def deletePlayerScore(player: Any, objective: str) -> bool: ...
    @staticmethod
    def getTime() -> int: ...
    @staticmethod
    def setTime(time: int) -> bool: ...
    @staticmethod
    def getWeather() -> int: ...
    @staticmethod
    def setWeather(weather: int) -> bool: ...
    # 兼容性方法
    @staticmethod
    def getAllScoreObjective() -> List[Any]: ...
    @staticmethod
    def getDisplayObjectives(slot: str) -> Any: ...
    @staticmethod
    def crash() -> None: ...
    @staticmethod
    def setMaxPlayers(count: int) -> bool: ...
       
class NBT:
    @staticmethod
    def parseSNBT(snbt: str) -> Any: ...
    @staticmethod
    def parseBinaryNBT(data: Any) -> Any: ...
    @property
    def End(self) -> int: ...
    @property
    def Byte(self) -> int: ...
    @property
    def Short(self) -> int: ...
    @property
    def Int(self) -> int: ...
    @property
    def Long(self) -> int: ...
    @property
    def Float(self) -> int: ...
    @property
    def Double(self) -> int: ...
    @property
    def ByteArray(self) -> int: ...
    @property
    def String(self) -> int: ...
    @property
    def List(self) -> int: ...
    @property
    def Compound(self) -> int: ...
    @staticmethod
    def createTag(type: int, value: Any = None) -> Any: ...
    @staticmethod
    def newTag(type: int, value: Any = None) -> Any: ...

class NbtByte:
    def __init__(self, value: int) -> None: ...
    def getType(self) -> int: ...
    def toString(self, indent: int = -1) -> str: ...
    def set(self, value: int) -> bool: ...
    def get(self) -> int: ...

class NbtShort:
    def __init__(self, value: int) -> None: ...
    def getType(self) -> int: ...
    def toString(self, indent: int = -1) -> str: ...
    def set(self, value: int) -> bool: ...
    def get(self) -> int: ...

class NbtInt:
    def __init__(self, value: int) -> None: ...
    def getType(self) -> int: ...
    def toString(self, indent: int = -1) -> str: ...
    def set(self, value: int) -> bool: ...
    def get(self) -> int: ...

class NbtLong:
    def __init__(self, value: int) -> None: ...
    def getType(self) -> int: ...
    def toString(self, indent: int = -1) -> str: ...
    def set(self, value: int) -> bool: ...
    def get(self) -> int: ...

class NbtFloat:
    def __init__(self, value: float) -> None: ...
    def getType(self) -> int: ...
    def toString(self, indent: int = -1) -> str: ...
    def set(self, value: float) -> bool: ...
    def get(self) -> float: ...

class NbtDouble:
    def __init__(self, value: float) -> None: ...
    def getType(self) -> int: ...
    def toString(self, indent: int = -1) -> str: ...
    def set(self, value: float) -> bool: ...
    def get(self) -> float: ...

class NbtString:
    def __init__(self, value: str) -> None: ...
    def getType(self) -> int: ...
    def toString(self, indent: int = -1) -> str: ...
    def set(self, value: str) -> bool: ...
    def get(self) -> str: ...

class NbtByteArray:
    def __init__(self, data: Any) -> None: ...
    def getType(self) -> int: ...
    def toString(self, indent: int = -1) -> str: ...
    def set(self, data: Any) -> bool: ...
    def get(self) -> Any: ...

class NbtList:
    def __init__(self, data: List[Any] = None) -> None: ...
    def getType(self) -> int: ...
    def toString(self, indent: int = -1) -> str: ...
    def getSize(self) -> int: ...
    def getTypeOf(self, index: int) -> int: ...
    def setEnd(self, index: int) -> Any: ...
    def setByte(self, index: int, value: int) -> Any: ...
    def setInt(self, index: int, value: int) -> Any: ...
    def setShort(self, index: int, value: int) -> Any: ...
    def setLong(self, index: int, value: int) -> Any: ...
    def setFloat(self, index: int, value: float) -> Any: ...
    def setDouble(self, index: int, value: float) -> Any: ...
    def setString(self, index: int, value: str) -> Any: ...
    def setByteArray(self, index: int, data: Any) -> Any: ...
    def setTag(self, index: int, tag: Any) -> Any: ...
    def addTag(self, tag: Any) -> Any: ...
    def removeTag(self, index: int) -> Any: ...
    def getData(self, index: int) -> Any: ...
    def getTag(self, index: int) -> Any: ...
    def toArray(self) -> List[Any]: ...

class NbtCompound:
    def __init__(self, data: Any = None) -> None: ...
    def getType(self) -> int: ...
    def toString(self, indent: int = -1) -> str: ...
    def getKeys(self) -> List[str]: ...
    def getTypeOf(self, key: str) -> int: ...
    def setEnd(self, key: str) -> Any: ...
    def setByte(self, key: str, value: int) -> Any: ...
    def setInt(self, key: str, value: int) -> Any: ...
    def setShort(self, key: str, value: int) -> Any: ...
    def setLong(self, key: str, value: int) -> Any: ...
    def setFloat(self, key: str, value: float) -> Any: ...
    def setDouble(self, key: str, value: float) -> Any: ...
    def setString(self, key: str, value: str) -> Any: ...
    def setByteArray(self, key: str, data: Any) -> Any: ...
    def setTag(self, key: str, tag: Any) -> Any: ...
    def removeTag(self, key: str) -> Any: ...
    def getData(self, key: str) -> Any: ...
    def getTag(self, key: str) -> Any|None: ...
    def toObject(self) -> Any: ...
    def toSNBT(self, indent: int = -1) -> str: ...
    def toBinaryNBT(self) -> Any: ...
    def destroy(self) -> bool: ...

class WSClientEvents:
    onTextReceived = 0
    onBinaryReceived = 1
    onError = 2
    onLostConnection = 3
    EVENT_COUNT = 4

class HttpRequestType:
    Get = 0
    Post = 1
    Put = 2
    Delete = 3
    Options = 4
    Patch = 5
    Head = 6

class Direction:
    NEG_Y = 0
    POS_Y = 1
    NEG_Z = 2
    POS_Z = 3
    NEG_X = 4
    POS_X = 5

class PointSize:
    PX1 = 1
    PX2 = 2
    PX4 = 4
    PX8 = 8
    PX16 = 16

class NumType:
    NUM0 = 0
    NUM1 = 1
    NUM2 = 2
    NUM3 = 3
    NUM4 = 4
    NUM5 = 5
    NUM6 = 6
    NUM7 = 7
    NUM8 = 8
    NUM9 = 9
    NUMA = 'A'
    NUMB = 'B'
    NUMC = 'C'
    NUMD = 'D'
    NUME = 'E'
    NUMF = 'F'
    NUM10 = 10
    NUM11 = 11
    NUM12 = 12
    NUM13 = 13
    NUM14 = 14
    NUM15 = 15
    NUM16 = 16

class ColorPalette:
    BLACK = 0
    INDIGO = 1
    LAVENDER = 2
    TEAL = 3
    COCOA = 4
    DARK = 5
    OATMEAL = 6
    WHITE = 7
    RED = 8
    APRICOT = 9
    YELLOW = 10
    GREEN = 11
    VATBLUE = 12
    SLATE = 13
    PINK = 14
    FAWN = 15

class network:
    @staticmethod
    def httpGet(url: str, headers: Optional[Dict[str, str]] = None, callback: Optional[Callable] = None) -> bool: ...
    @staticmethod
    def httpPost(url: str, data: str, type: str, callback: Callable) -> bool: ...
    @staticmethod
    def httpGetSync(url: str) -> Dict[str, Any]: ...
    @staticmethod
    def newWebSocket() -> 'WSClient': ...

class WSClient:
    Open: int
    Closing: int
    Closed: int
    def __init__(self, *arg: Any, **kwargs: Any) -> None: ...
    @property
    def status(self) -> int: ...
    def connect(self, target: str) -> bool: ...
    def connectAsync(self, target: str, callback: Callable) -> bool: ...
    def send(self, data: Union[str, Any]) -> bool: ...
    def listen(self, event: str, func: Callable) -> bool: ...
    def close(self) -> bool: ...
    def shutdown(self) -> bool: ...
    def errorCode(self) -> int: ...

class HttpServer:
    def __init__(self, *arg: Any, **kwargs: Any) -> None: ...
    def onGet(self, path: str, func: Callable) -> 'HttpServer': ...
    def onPut(self, path: str, func: Callable) -> 'HttpServer': ...
    def onPost(self, path: str, func: Callable) -> 'HttpServer': ...
    def onPatch(self, path: str, func: Callable) -> 'HttpServer': ...
    def onDelete(self, path: str, func: Callable) -> 'HttpServer': ...
    def onOptions(self, path: str, func: Callable) -> 'HttpServer': ...
    def onPreRouting(self, func: Callable) -> 'HttpServer': ...
    def onPostRouting(self, func: Callable) -> 'HttpServer': ...
    def onError(self, func: Callable) -> 'HttpServer': ...
    def onException(self, func: Callable) -> 'HttpServer': ...
    @Overload
    def listen(self, port: int) -> 'HttpServer': ...
    @Overload
    def listen(self, addr: str, port: int) -> 'HttpServer': ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    def isRunning(self) -> bool: ...

class HttpRequest:
    def __init__(self, *arg: Any, **kwargs: Any) -> None: ...
    def getHeader(self, key: str) -> List[str]: ...
    @property
    def headers(self) -> Dict[str, List[str]]: ...
    @property
    def method(self) -> str: ...
    @property
    def body(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def params(self) -> Dict[str, Union[str, List[str]]]: ...
    @property
    def query(self) -> Dict[str, Union[str, List[str]]]: ...
    @property
    def remoteAddr(self) -> str: ...
    @property
    def remotePort(self) -> int: ...
    @property
    def version(self) -> str: ...
    @property
    def matches(self) -> List[str]: ...

class HttpResponse:
    def __init__(self, *arg: Any, **kwargs: Any) -> None: ...
    def getHeader(self, key: str) -> List[str]: ...
    def setHeader(self, key: str, value: str) -> 'HttpResponse': ...
    def write(self, *args: Any) -> 'HttpResponse': ...
    @property
    def headers(self) -> Dict[str, List[str]]: ...
    @headers.setter
    def headers(self, value: Dict[str, List[str]]) -> None: ...
    @property
    def status(self) -> int: ...
    @status.setter
    def status(self, value: int) -> None: ...
    @property
    def body(self) -> str: ...
    @body.setter
    def body(self, value: str) -> None: ...
    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, value: str) -> None: ...
    @property
    def reason(self) -> str: ...
    @reason.setter
    def reason(self, value: str) -> None: ...

class LLSE_Packet:
    def getName(self) -> str: ...
    def getId(self) -> int: ...

class BinaryStream:
    def __init__(self, *arg: Any, **kwargs: Any) -> None: ...
    def getData(self) -> str: ...
    def reset(self) -> bool: ...
    def reserve(self, size: int) -> bool: ...
    def writeBool(self, value: bool) -> bool: ...
    def writeByte(self, value: int) -> bool: ...
    def writeDouble(self, value: float) -> bool: ...
    def writeFloat(self, value: float) -> bool: ...
    def writeSignedBigEndianInt(self, value: int) -> bool: ...
    def writeSignedInt(self, value: int) -> bool: ...
    def writeSignedInt64(self, value: int) -> bool: ...
    def writeSignedShort(self, value: int) -> bool: ...
    def writeString(self, value: str) -> bool: ...
    def writeUnsignedChar(self, value: int) -> bool: ...
    def writeUnsignedInt(self, value: int) -> bool: ...
    def writeUnsignedInt64(self, value: int) -> bool: ...
    def writeUnsignedShort(self, value: int) -> bool: ...
    def writeUnsignedVarInt(self, value: int) -> bool: ...
    def writeUnsignedVarInt64(self, value: int) -> bool: ...
    def writeVarInt(self, value: int) -> bool: ...
    def writeVarInt64(self, value: int) -> bool: ...
    def writeVec3(self, pos: Any) -> bool: ...
    def writeBlockPos(self, pos: Any) -> bool: ...
    def writeCompoundTag(self, nbt: Any) -> bool: ...
    def writeItem(self, item: Any) -> bool: ...
    def createPacket(self, packetId: int) -> 'LLSE_Packet': ...

class ParticleSpawner:
    def __init__(self, *arg: Any, **kwargs: Any) -> None: ...
    @property
    def displayRadius(self) -> int: ...
    @displayRadius.setter
    def displayRadius(self, value: int) -> None: ...
    @property
    def highDetial(self) -> bool: ...
    @highDetial.setter
    def highDetial(self, value: bool) -> None: ...
    @property
    def doubleSide(self) -> bool: ...
    @doubleSide.setter
    def doubleSide(self, value: bool) -> None: ...
    def spawnParticle(self, pos: Any, particleName: str) -> bool: ...
    def drawPoint(self, *args: Any) -> bool: ...
    def drawNumber(self, *args: Any) -> bool: ...
    def drawAxialLine(self, *args: Any) -> bool: ...
    def drawOrientedLine(self, *args: Any) -> bool: ...
    def drawCuboid(self, *args: Any) -> bool: ...
    def drawCircle(self, *args: Any) -> bool: ...

class ParticleColor:
    Black: str = "B"
    Indigo: str = "I"
    Lavender: str = "L"
    Teal: str = "T"
    Cocoa: str = "C"
    Dark: str = "D"
    Oatmeal: str = "O"
    White: str = "W"
    Red: str = "R"
    Apricot: str = "A"
    Yellow: str = "Y"
    Green: str = "G"
    Vatblue: str = "V"
    Slate: str = "S"
    Pink: str = "P"
    Fawn: str = "F"

class LLSE_Player:
    @property
    def name(self) -> str: ...
    @property
    def pos(self) -> Any: ...
    @property
    def feetPos(self) -> FloatPos: ...
    @property
    def blockPos(self) -> IntPos: ...
    @property
    def lastDeathPos(self) -> Any: ...
    @property
    def realName(self) -> str: ...
    @property
    def xuid(self) -> str: ...
    @property
    def uuid(self) -> str: ...
    @property
    def permLevel(self) -> int: ...
    @property
    def gameMode(self) -> int: ...
    @property
    def canSleep(self) -> bool: ...
    @property
    def canFly(self) -> bool: ...
    @property
    def canBeSeenOnMap(self) -> bool: ...
    @property
    def canFreeze(self) -> bool: ...
    @property
    def canSeeDaylight(self) -> bool: ...
    @property
    def canShowNameTag(self) -> bool: ...
    @property
    def canStartSleepInBed(self) -> bool: ...
    @property
    def canPickupItems(self) -> bool: ...
    @property
    def maxHealth(self) -> int: ...
    @property
    def health(self) -> int: ...
    @property
    def inAir(self) -> bool: ...
    @property
    def inWater(self) -> bool: ...
    @property
    def inLava(self) -> bool: ...
    @property
    def inRain(self) -> bool: ...
    @property
    def inSnow(self) -> bool: ...
    @property
    def inWall(self) -> bool: ...
    @property
    def inWaterOrRain(self) -> bool: ...
    @property
    def inWorld(self) -> bool: ...
    @property
    def inClouds(self) -> bool: ...
    @property
    def speed(self) -> float: ...
    @property
    def direction(self) -> Any: ...
    @property
    def uniqueId(self) -> str: ...
    @property
    def runtimeId(self) -> str: ...
    @property
    def langCode(self) -> str: ...
    @property
    def isLoading(self) -> bool: ...
    @property
    def isInvisible(self) -> bool: ...
    @property
    def isInsidePortal(self) -> bool: ...
    @property
    def isHurt(self) -> bool: ...
    @property
    def isTrusting(self) -> bool: ...
    @property
    def isTouchingDamageBlock(self) -> bool: ...
    @property
    def isHungry(self) -> bool: ...
    @property
    def isOnFire(self) -> bool: ...
    @property
    def isOnGround(self) -> bool: ...
    @property
    def isOnHotBlock(self) -> bool: ...
    @property
    def isTrading(self) -> bool: ...
    @property
    def isAdventure(self) -> bool: ...
    @property
    def isGliding(self) -> bool: ...
    @property
    def isSurvival(self) -> bool: ...
    @property
    def isSpectator(self) -> bool: ...
    @property
    def isRiding(self) -> bool: ...
    @property
    def isDancing(self) -> bool: ...
    @property
    def isCreative(self) -> bool: ...
    @property
    def isFlying(self) -> bool: ...
    @property
    def isSleeping(self) -> bool: ...
    @property
    def isMoving(self) -> bool: ...
    @property
    def isSneaking(self) -> bool: ...
    @property
    def sneaking(self) -> bool: ...
    @property
    def ip(self) -> str: ...
    def isOP(self) -> bool: ...
    def setPermLevel(self, level: int) -> bool: ...
    def setGameMode(self, mode: int) -> bool: ...
    def runcmd(self, command: str) -> bool: ...
    @Overload
    def teleport(self, pos: Any) -> bool: ...
    @Overload
    def teleport(self, x: float, y: float, z: float, dimId: int) -> bool: ...
    def kill(self) -> bool: ...
    def kick(self, msg: str = "") -> bool: ...
    def disconnect(self, msg: str = "") -> bool: ...
    def tell(self, msg: str, type: Optional[int] = None) -> bool: ...
    def talkAs(self, msg: str) -> bool: ...
    def talkTo(self, msg: str, target: 'LLSE_Player') -> bool: ...
    def sendText(self, msg: str, type: Optional[int] = None) -> bool: ...
    def setTitle(self, content: str, type: Optional[int] = None, fadeInTime: Optional[int] = None, stayTime: Optional[int] = None, fadeOutTime: Optional[int] = None) -> bool: ...
    def rename(self, name: str) -> bool: ...
    def setFire(self, time: int, isEffectValue: bool) -> bool: ...
    def stopFire(self) -> bool: ...
    def transServer(self, addr: str, port: int) -> bool: ...
    def crash(self) -> bool: ...
    def hurt(self, damage: float, type: Optional[int] = None, source: Optional[Any] = None) -> bool: ...
    def heal(self, amount: int) -> bool: ...
    def setHealth(self, health: float) -> bool: ...
    def setMaxHealth(self, maxHealth: float) -> bool: ...
    def setAbsorption(self, value: float) -> bool: ...
    def setAttackDamage(self, damage: float) -> bool: ...
    def setMaxAttackDamage(self, maxDamage: float) -> bool: ...
    def setFollowRange(self, range: float) -> bool: ...
    def setKnockbackResistance(self, resistance: float) -> bool: ...
    def setLuck(self, luck: float) -> bool: ...
    def setMovementSpeed(self, speed: float) -> bool: ...
    def setUnderwaterMovementSpeed(self, speed: float) -> bool: ...
    def setLavaMovementSpeed(self, speed: float) -> bool: ...
    def setHungry(self, value: float) -> bool: ...
    def refreshChunks(self) -> bool: ...
    def giveItem(self, item: Any, count: Optional[int] = None) -> bool: ...
    def clearItem(self, typeName: str, count: Optional[int] = None) -> int: ...
    def isSprinting(self) -> bool: ...
    def setSprinting(self, sprinting: bool) -> bool: ...
    def sendToast(self, title: str, content: str) -> bool: ...
    def distanceTo(self, target: Any) -> float: ...
    def distanceToSqr(self, target: Any) -> float: ...
    def getBlockStandingOn(self) -> Any: ...
    def getDevice(self) -> Any: ...
    def getHand(self) -> LLSE_Item: ...
    def getOffHand(self) -> Any: ...
    def getInventory(self) -> LLSE_Container: ...
    def getArmor(self) -> Any: ...
    def getEnderChest(self) -> Any: ...
    def getRespawnPosition(self) -> Any: ...
    def setRespawnPosition(self, pos: Any) -> bool: ...
    def refreshItems(self) -> bool: ...
    def getScore(self, objective: str) -> int: ...
    def setScore(self, objective: str, score: int) -> bool: ...
    def addScore(self, objective: str, score: int) -> bool: ...
    def reduceScore(self, objective: str, score: int) -> bool: ...
    def deleteScore(self, objective: str) -> bool: ...
    def setSidebar(self, title: str, data: Dict[str, int], sortOrder: Optional[int] = None) -> bool: ...
    def removeSidebar(self) -> bool: ...
    @Overload
    def setBossBar(self, name: str, percent: int, color: Optional[int] = None) -> bool: ...
    @Overload
    def setBossBar(self, uid: int, name: str, percent: int, color: int) -> bool: ...
    @Overload
    def removeBossBar(self) -> bool: ...
    @Overload
    def removeBossBar(self, uid: int) -> bool: ...
    def addLevel(self, levels: int) -> bool: ...
    def reduceLevel(self, levels: int) -> bool: ...
    def getLevel(self) -> int: ...
    def setLevel(self, level: int) -> bool: ...
    def setScale(self, scale: float) -> bool: ...
    def resetLevel(self) -> bool: ...
    def addExperience(self, exp: int) -> bool: ...
    def reduceExperience(self, exp: int) -> bool: ...
    def getCurrentExperience(self) -> int: ...
    def setCurrentExperience(self, exp: int) -> bool: ...
    def getTotalExperience(self) -> int: ...
    def setTotalExperience(self, exp: int) -> bool: ...
    def getXpNeededForNextLevel(self) -> int: ...
    def setAbility(self, abilityIndex: int, value: bool) -> bool: ...
    def getBiomeId(self) -> int: ...
    def getBiomeName(self) -> str: ...
    def getAllEffects(self) -> List[int]: ...
    def addEffect(self, effectId: int, duration: int, level: int, showParticles: bool) -> bool: ...
    def removeEffect(self, effectId: int) -> bool: ...
    def sendSimpleForm(self, title: str, content: str, buttons: List[str], images: List[str], callback: Callable, update: Optional[bool] = None) -> int: ...
    def sendModalForm(self, title: str, content: str, button1: str, button2: str, callback: Callable, update: Optional[bool] = None) -> int: ...
    def sendCustomForm(self, formData: str, callback: Callable, update: Optional[bool] = None) -> int: ...
    def sendForm(self, form: Any, callback: Callable, update: Optional[bool] = None) -> bool: ...
    def closeForm(self) -> bool: ...
    def sendPacket(self, packet: Any) -> bool: ...
    def setExtraData(self, key: str, value: Any) -> bool: ...
    def getExtraData(self, key: str) -> Any: ...
    def delExtraData(self, key: str) -> bool: ...
    def getNbt(self) -> Any: ...
    def setNbt(self, nbt: Any) -> bool: ...
    def addTag(self, tag: str) -> bool: ...
    def removeTag(self, tag: str) -> bool: ...
    def hasTag(self, tag: str) -> bool: ...
    def getAllTags(self) -> List[str]: ...
    def getAbilities(self) -> Dict[str, Any]: ...
    def getAttributes(self) -> List[Dict[str, Any]]: ...
    def getEntityFromViewVector(self, maxDistance: Optional[float] = None) -> Any: ...
    def getBlockFromViewVector(self, includeLiquid: Optional[bool] = None, solidOnly: Optional[bool] = None, maxDistance: Optional[float] = None, fullOnly: Optional[bool] = None) -> Any: ...
    def isSimulatedPlayer(self) -> bool: ...
    def quickEvalMolangScript(self, script: str) -> float: ...
    def getMoney(self) -> int: ...
    def setMoney(self, amount: int) -> bool: ...
    def addMoney(self, amount: int) -> bool: ...
    def reduceMoney(self, amount: int) -> bool: ...
    def transMoney(self, target: Union[str, 'LLSE_Player'], amount: int, note: Optional[str] = None) -> bool: ...
    def getMoneyHistory(self, count: int) -> Any: ...
    def getAllItems(self) -> Dict[str, Any]: ...
    def removeItem(self, inventoryId: int, count: int) -> bool: ...
    def setOnFire(self, time: int) -> bool: ...
    def setTag(self, nbt: Any) -> bool: ...
    def getTag(self) -> Any: ...
    def removeScore(self, objective: str) -> bool: ...
    def distanceToPos(self, pos: Any) -> float: ...
    def toEntity(self) -> Any: ...
    def simulateSneak(self, *args: Any) -> bool: ...
    def simulateAttack(self, *args: Any) -> bool: ...
    def simulateDestroy(self, *args: Any) -> bool: ...
    def simulateDisconnect(self, *args: Any) -> bool: ...
    def simulateInteract(self, *args: Any) -> bool: ...
    def simulateRespawn(self, *args: Any) -> bool: ...
    def simulateJump(self, *args: Any) -> bool: ...
    def simulateLocalMove(self, *args: Any) -> bool: ...
    def simulateWorldMove(self, *args: Any) -> bool: ...
    def simulateMoveTo(self, *args: Any) -> bool: ...
    def simulateLookAt(self, *args: Any) -> bool: ...
    def simulateSetBodyRotation(self, *args: Any) -> bool: ...
    def simulateNavigateTo(self, *args: Any) -> bool: ...
    def simulateUseItem(self, *args: Any) -> bool: ...
    def simulateStopDestroyingBlock(self, *args: Any) -> bool: ...
    def simulateStopInteracting(self, *args: Any) -> bool: ...
    def simulateStopMoving(self, *args: Any) -> bool: ...
    def simulateStopUsingItem(self, *args: Any) -> bool: ...
    def simulateStopSneaking(self, *args: Any) -> bool: ...
    
class system:
    @staticmethod
    def getTimeStr() -> str: ...
    @staticmethod
    def getTimeObj() -> dict: ...
    @staticmethod
    def randomGuid() -> str: ...
    @staticmethod
    @Overload
    def cmd(command: str, callback: Any) -> bool: ...
    @staticmethod
    @Overload
    def cmd(command: str, callback: Any, timeLimit: int) -> bool: ...
    @staticmethod
    def cmd(*args) -> bool: ...
    @staticmethod
    @Overload
    def newProcess(process: str, callback: Any) -> bool: ...
    @staticmethod
    @Overload
    def newProcess(process: str, callback: Any, timeLimit: int) -> bool: ...
    @staticmethod
    def newProcess(*args) -> bool: ...
